Repository sparcs-kaist/students, pull requests merged in 2025-06, with the labels that each got.

#240 231 impl zod to openapi
  packages/api/package.json
  packages/api/src/app.module.ts
  packages/api/src/feature/auth/controller/auth.controller.ts
  packages/api/src/feature/semester/controller/semester.controller.ts
  packages/api/src/feature/semester/semester.module.ts
  packages/api/src/feature/semester/service/semester.service.ts
  packages/api/src/feature/semester/type/semester.model.ts
  packages/api/src/main.ts
  packages/interface/package.json
  packages/interface/src/api/auth/endpoint/apiAut001.ts
  packages/interface/src/api/auth/endpoint/apiAut002.ts
  packages/interface/src/api/auth/endpoint/apiAut003.ts
  packages/interface/src/api/auth/endpoint/apiAut004.ts
  packages/interface/src/api/auth/index.ts
  packages/interface/src/api/organization/type/organization.student.type.ts
  packages/interface/src/api/semester/endpoint/apiSem001.ts
  packages/interface/src/api/semester/index.ts
  packages/interface/src/api/semester/type/semester.type.ts
  packages/interface/src/open-api.ts
  pnpm-lock.yaml
Labels: documentation, enhancement, backend

#154 Impl file module
  .eslintrc
  package-lock.json
  package.json
  packages/api/package.json
  packages/api/src/app.module.ts
  packages/api/src/common/util/decorators/method-decorator.ts
  packages/api/src/common/util/decorators/param-decorator.ts
  packages/api/src/feature/file/controller/file.controller.ts
  packages/api/src/feature/file/file.module.ts
  packages/api/src/feature/file/file.util.ts
  packages/api/src/feature/file/model/file.model.ts
  packages/api/src/feature/file/repository/file.repository.ts
  packages/api/src/feature/file/service/file.public.service.ts
  packages/api/src/feature/file/service/file.service.ts
  packages/interface/src/api/_example/endpoint/apiTmp000.ts
  packages/interface/src/api/file/endpoint/apiFil001.ts
  packages/interface/src/api/file/index.ts
  packages/interface/src/api/file/type/file.type.ts
  packages/interface/src/api/semester/index.ts
  packages/interface/src/api/user/index.ts
  pnpm-lock.yaml
Labels: enhancement, backend

#243 Fix Operation Proposal Entity
  packages/api/src/app.module.ts
  packages/api/src/drizzle/schema/project-proposal.schema.ts
  packages/api/src/feature/proposal/controller/proposal.controller.ts
  packages/api/src/feature/proposal/model/operating-committee-proposal-revision.model.ts
  packages/api/src/feature/proposal/model/operating-committee-proposal.model.ts
  packages/api/src/feature/proposal/model/operation-proposal-revision.model.ts
  packages/api/src/feature/proposal/model/project-proposal.model.ts
  packages/api/src/feature/proposal/proposal.module.ts
  packages/api/src/feature/proposal/repository/operating-committee-proposal-revision.repository.ts
  packages/api/src/feature/proposal/repository/operating-committee-proposal.repository.ts
  packages/api/src/feature/proposal/repository/operation-proposal-revision.repository.ts
  packages/api/src/feature/proposal/repository/project-proposal-revision.repository.ts
  packages/api/src/feature/proposal/service/proposal.service.ts
  packages/interface/src/api/proposal/endpoint/apiPrp021.ts
  packages/interface/src/api/proposal/endpoint/apiPrp026.ts
  packages/interface/src/api/proposal/endpoint/apiPrp027.ts
  packages/interface/src/api/proposal/endpoint/apiPrp028.ts
  packages/interface/src/api/proposal/endpoint/apiPrp029.ts
  packages/interface/src/api/proposal/endpoint/apiPrp030.ts
  packages/interface/src/api/proposal/index.ts
  packages/interface/src/api/proposal/type/operating-committee-proposal.type.ts
  packages/interface/src/api/proposal/type/operation-proposal.type.ts
Labels: backend

#244 235 impl GroupDetail Comp fold
  packages/web/src/features/document-lookup/project/components/_atomic/GroupDetail.tsx
Labels: frontend
