Repository sparcs-kaist/students, pull requests merged in 2025-04, with the labels that each got.

#114 impl project timeline component
  packages/web/package.json
  packages/web/src/common/components/DateInput.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/features/project/components/ProjectTimelineTable.tsx
  packages/web/src/features/project/components/_atomic/TimelineDateInput.tsx
  packages/web/src/features/project/services/_mock/mockProjectTimelineData.ts
  pnpm-lock.yaml
Labels: enhancement, frontend

#140 feat: petition, petitonAnswer, petitionAgree repository
  packages/api/src/drizzle/schema/index.ts
  packages/api/src/drizzle/schema/petition.schema.ts
  packages/api/src/feature/petition/repository/petition.agree.repository.ts
  packages/api/src/feature/petition/repository/petition.answer.repository.ts
  packages/api/src/feature/petition/repository/petition.repository.ts
  packages/api/src/feature/petition/type/petition.agree.model.ts
  packages/api/src/feature/petition/type/petition.answer.model.ts
  packages/api/src/feature/petition/type/petition.model.ts
  packages/interface/src/api/petition/type/petition.type.ts
  packages/interface/src/common/enum/petition.enum.ts
Labels: backend

#162 Refactor project table design
  packages/web/src/app/document-lookup/project-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/project-report/result/[id]/page.tsx
  packages/web/src/common/components/HoverClickText.tsx
  packages/web/src/features/project/components/ProjectTable.tsx
  packages/web/src/features/project/components/ReviewerProjectTable.tsx
  packages/web/src/features/project/services/_mock/mockProjectProposalData.ts
Labels: enhancement, frontend

#164 revise design of doc lookup threeinput component
  packages/web/src/app/document-lookup/budget-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/budget-report/result/[id]/page.tsx
  packages/web/src/app/document-lookup/page.tsx
  packages/web/src/app/document-lookup/project-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/project-report/result/[id]/page.tsx
  packages/web/src/common/components/Radio/RadioButton.tsx
  packages/web/src/common/components/Radio/RadioOption.tsx
  packages/web/src/common/components/Select/Dropdown.tsx
  packages/web/src/common/components/Select/index.tsx
  packages/web/src/common/components/SelectCard/DocumentTypeSelectCard.tsx
  packages/web/src/common/components/SelectCard/OrganizationSelectCard.tsx
  packages/web/src/common/components/SelectCard/SemesterSelectCard.tsx
  packages/web/src/features/documents/components/ThreeInput/index.tsx
Labels: frontend

#23 impl multi prop into select
  packages/web/src/app/favicon.ico
  packages/web/src/common/components/MultiSelect/Dropdown.tsx
  packages/web/src/common/components/MultiSelect/SelectOption.tsx
  packages/web/src/common/components/MultiSelect/_atomic/NoOption.tsx
  packages/web/src/common/components/MultiSelect/index.tsx
  packages/web/src/common/components/SelectCard/OrganizationSelectCard.tsx
  packages/web/stories/Forms/MultiSelect.stories.tsx
  packages/web/tsconfig.json
Labels: enhancement, frontend

#141 impl viewr project report detail page
  .env
  packages/web/src/app/document-lookup/project-report/result/[id]/detail/[detailId]/page.tsx
  packages/web/src/common/components/Forms/TextAreaInput.tsx
  packages/web/src/common/components/Table/Table.tsx
  packages/web/src/common/components/Table/TableCell.tsx
  packages/web/src/features/documents/components/BudgetReportTable.tsx
  packages/web/src/features/documents/components/DocumentTimelineTable.tsx
  packages/web/src/features/documents/services/_mock/mockBudgetReportTable.tsx
  packages/web/src/features/documents/services/_mock/mockDocumentTimelineTable.tsx
Labels: enhancement, frontend

#174 feat: create mock data for budgetProposal and projectProposal
  packages/web/src/app/document-lookup/project-report/result/[id]/detail/[detailId]/page.tsx
  packages/web/src/features/document-lookup/budget/components/ManagerExpenditureTable.tsx
  packages/web/src/features/document-lookup/budget/services/_mock/mockBudgetReportTable.tsx
  packages/web/src/features/document-lookup/budget/services/_mock/mockManagerFormData.ts
  packages/web/src/features/document-lookup/budget/type/managerFormValues.ts
  packages/web/src/features/document-lookup/project/services/_mock/mockProjectProposalTable.ts
  packages/web/src/features/document-lookup/project/type/managerFormValues.ts
Labels: enhancement, frontend

#177 File Table Schema
  packages/api/src/drizzle/schema/file.schema.ts
Labels: enhancement, backend

#185 Interface ExtractId Util
  packages/interface/src/common/type/ids.ts
  packages/interface/src/common/util.ts
Labels: enhancement

#181 Tidy up directory (project)
  packages/web/src/app/document-lookup/budget-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/project-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/project-report/result/[id]/page.tsx
  packages/web/src/common/components/Forms/TextAreaInput.tsx
  packages/web/src/features/document-lookup/project/components/GroupList.tsx
  packages/web/src/features/document-lookup/project/components/MemberTable.tsx
  packages/web/src/features/document-lookup/project/components/OperationPlan.tsx
  packages/web/src/features/document-lookup/project/components/ProjectTable.tsx
  packages/web/src/features/document-lookup/project/components/ProjectTimelineTable.tsx
  packages/web/src/features/document-lookup/project/components/ReviewOperationPlan.tsx
  packages/web/src/features/document-lookup/project/components/_atomic/GroupDetail.tsx
  packages/web/src/features/document-lookup/project/components/_atomic/TimelineDateInput.tsx
  packages/web/src/features/document-lookup/project/frames/ReviewerProjectProposalFrame.tsx
  packages/web/src/features/document-lookup/project/frames/ReviewerProjectReportFrame.tsx
  packages/web/src/features/document-lookup/project/frames/ViewerProjectProposalFrame.tsx
  packages/web/src/features/document-lookup/project/frames/ViewerProjectReportFrame.tsx
  packages/web/src/features/document-lookup/project/services/_mock/mockProjectProposalData.ts
  packages/web/src/features/document-lookup/project/services/_mock/mockProjectProposalTable.ts
  packages/web/src/features/document-lookup/project/services/_mock/mockProjectTimelineData.ts
  packages/web/src/features/document-lookup/project/type/managerFormValues.ts
Labels: enhancement, frontend

#187 Add review table to project proposal detail page (manager)
  packages/web/src/app/document-lookup/budget-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/budget-report/result/[id]/page.tsx
  packages/web/src/app/document-lookup/page.tsx
  packages/web/src/app/document-lookup/project-proposal/result/[id]/page.tsx
  packages/web/src/app/document-lookup/project-report/result/[id]/page.tsx
  packages/web/src/common/components/SelectCard/DocumentTypeSelectCard.tsx
  packages/web/src/features/document-lookup/project/components/ManagerProjectProposalReviewTable.tsx
  packages/web/src/features/document-lookup/project/frames/ManagerProjectProposalDetailFrame.tsx
Labels: enhancement, frontend
