Repository sparcs-kaist/students, pull requests merged in 2025-03, with the labels that each got.

#26 Implement /credits
  packages/web/src/app/credits/page.tsx
  packages/web/src/assets/sparcs-orange.svg
  packages/web/src/common/components/Card.tsx
  packages/web/src/common/components/FoldableSectionTitle.tsx
  packages/web/src/common/components/PageHead/_atomic/PageTitle.tsx
  packages/web/src/common/components/PageHead/index.tsx
  packages/web/src/common/components/SectionTitle.tsx
  packages/web/src/constants/paths.ts
  packages/web/src/features/credits/components/MemberCard.tsx
  packages/web/src/features/credits/components/MemberCardSection.tsx
  packages/web/src/features/credits/components/SemesterFoldableTitle.tsx
  packages/web/src/features/credits/credits.ts
  packages/web/src/styles/fonts/googleFonts.ts
  packages/web/src/styles/fonts/local/NanumSquare-ExtraBold.woff2
  packages/web/src/styles/themes/colors.ts
  packages/web/src/styles/themes/fonts.ts
Labels: enhancement, frontend

#106 Impl notice component
  packages/web/src/common/components/Icon.tsx
  packages/web/src/common/components/Notice.tsx
Labels: enhancement, frontend

#113 Add chacha's credit
  packages/web/src/features/credits/credits.ts
Labels: frontend

#127 feat: take functions
  packages/api/src/common/util/util.ts
Labels: backend

#142 Connect Nav and Add NotImplementedPage
  packages/web/src/app/activity-certificate/page.tsx
  packages/web/src/app/affiliation/page.tsx
  packages/web/src/app/agendas/page.tsx
  packages/web/src/app/central-executive-committee/page.tsx
  packages/web/src/app/forms/page.tsx
  packages/web/src/app/info/page.tsx
  packages/web/src/app/meetings/page.tsx
  packages/web/src/app/notice/page.tsx
  packages/web/src/app/petition/page.tsx
  packages/web/src/app/rules/page.tsx
  packages/web/src/constants/nav.ts
  packages/web/src/constants/paths.ts
  packages/web/src/features/NotImplemented/NotImplementedComponent.tsx
Labels: enhancement, frontend

#134 Impl budget report reviewer page
  packages/web/src/app/document-lookup/budget-report/result/[id]/page.tsx
  packages/web/src/common/components/Table/Table.tsx
  packages/web/src/features/documents/components/ReviewModal.tsx
  packages/web/src/features/documents/components/ReviewerExpenditureTable.tsx
Labels: enhancement, frontend
