Repository sparcs-kaist/students, pull requests merged in 2025-05, with the labels that each got.

#189 Fix i18n error
  packages/web/src/i18n/messages/en.json
  packages/web/src/i18n/messages/ko.json
Labels: bug, frontend

#191 Make modal background gray
  packages/web/src/common/components/Modal/index.tsx
Labels: enhancement, frontend

#195 Fix various warnings
  packages/web/src/common/components/Buttons/TextButton.tsx
  packages/web/src/common/components/Calendar/Calendar.tsx
  packages/web/src/common/components/Calendar/_atomic/CalendarDate.tsx
  packages/web/src/common/components/Calendar/_atomic/MonthNavigator.tsx
  packages/web/src/common/components/Radio/index.tsx
  packages/web/src/common/components/Table/SingleColumnTable.tsx
  packages/web/src/common/components/Typography.tsx
Labels: bug, frontend

#197 총학 소개 페이지 구현
  .env
  .gitignore
  packages/web/src/app/credits/page.tsx
  packages/web/src/app/info/page.tsx
  packages/web/src/common/components/PageHead/index.tsx
  packages/web/src/features/info/components/Content.tsx
  packages/web/src/features/info/mock.ts
Labels: enhancement, frontend

#203 Fix Base Repository Bugs
  package.json
  packages/api/package.json
  packages/api/src/common/base/base.multi.repository.ts
  packages/api/src/common/base/base.repository.ts
  packages/api/src/common/base/base.single.repository.ts
  packages/api/src/drizzle/drizzle.module.ts
  packages/api/src/drizzle/schema/budget-proposal.schema.ts
  packages/api/src/drizzle/schema/budget-report.schema.ts
  packages/api/src/drizzle/schema/file.schema.ts
  packages/api/src/drizzle/schema/organization.schema.ts
  packages/api/src/drizzle/schema/project-proposal.schema.ts
  packages/api/src/drizzle/schema/project-report.schema.ts
Labels: bug, backend

#206 Fix ref errors on input
  packages/web/src/common/components/Forms/TextAreaInput.tsx
  packages/web/src/common/components/Forms/TextInput.tsx
Labels: bug, frontend

#217 feat: isremoved field for revisions
  packages/api/src/common/base/revision-entity.model.ts
  packages/api/src/drizzle/schema/budget-proposal.schema.ts
  packages/api/src/drizzle/schema/budget-report.schema.ts
  packages/api/src/drizzle/schema/project-proposal.schema.ts
  packages/api/src/drizzle/schema/project-report.schema.ts
  packages/api/src/feature/proposal/repository/budget-proposal-expense-revision.repository.ts
  packages/api/src/feature/proposal/repository/budget-proposal-income-revision.repository.ts
  packages/api/src/feature/proposal/repository/operating-committee-proposal-revision.repository.ts
  packages/api/src/feature/proposal/repository/operation-proposal-revision.repository.ts
  packages/api/src/feature/proposal/repository/project-proposal-revision.repository.ts
  packages/interface/src/common/type/revision-base.type.ts
Labels: enhancement, backend

#210 Make operating committee member table
  packages/web/src/features/document-lookup/project/components/ManageOperationPlan.tsx
  packages/web/src/features/document-lookup/project/components/OperatingCommitteeMemberTable.tsx
  packages/web/src/features/document-lookup/project/services/_mock/mockProjectProposalData.ts
Labels: frontend

#221 Impl member registration initial
  packages/web/src/app/organization-register/page.tsx
  packages/web/src/constants/nav.ts
  packages/web/src/constants/paths.ts
  packages/web/src/features/organization-register/components/OrganizationDescription.tsx
  packages/web/src/features/organization-register/services/_mock/mockOrganizationData.ts
  packages/web/src/i18n/messages/en.json
  packages/web/src/i18n/messages/ko.json
Labels: enhancement, frontend

#224 Impl manage member table
  packages/interface/src/common/enum/organization.enum.ts
  packages/web/src/app/organization-manage/[id]/page.tsx
  packages/web/src/common/components/Tag/LightTag.tsx
  packages/web/src/common/util/enumToItem.tsx
  packages/web/src/common/util/tableTagList.ts
  packages/web/src/features/document-lookup/budget/components/ManagerExpenditureTable.tsx
  packages/web/src/features/document-lookup/budget/components/ManagerExpenditureTableInProjectDetail.tsx
  packages/web/src/features/document-lookup/budget/components/ManagerIncomeTable.tsx
  packages/web/src/features/document-lookup/budget/components/ReviewerExpenditureTable.tsx
  packages/web/src/features/document-lookup/budget/components/ReviewerIncomeTable.tsx
  packages/web/src/features/document-lookup/budget/components/TotalTable.tsx
  packages/web/src/features/document-lookup/budget/components/ViewerExpenditureTable.tsx
  packages/web/src/features/document-lookup/budget/components/ViewerIncomeTable.tsx
  packages/web/src/features/document-lookup/project/components/BudgetReportTable.tsx
  packages/web/src/features/document-lookup/project/components/ManagerProjectProposalReviewTable.tsx
  packages/web/src/features/document-lookup/project/components/ManagerProjectProposalTable.tsx
  packages/web/src/features/document-lookup/project/components/ManagerProjectReportReviewTable.tsx
  packages/web/src/features/document-lookup/project/components/ManagerProjectReportTable.tsx
  packages/web/src/features/document-lookup/project/components/ProjectTable.tsx
  packages/web/src/features/organization-manage/components/ManageMemberTable.tsx
  packages/web/src/features/organization-manage/services/_mock/mockOrganizationManageData.ts
Labels: enhancement, frontend
